/**
 * forgedKeyFixture.test.ts (F-32.1/F-32.3, AC-153/AC-157, #136/#137) — the committed
 * self-minted-key forgery `docs/test-assets/sample-bundle-forged-key.pdf` is the
 * live-testable negative the red team drops on /verify. It must be:
 *   - INTEGRITY VERIFIED offline — internally self-consistent (DKIM verifies against the
 *     embedded attacker key, attachment/intent/real-.tsr all pass), yet honestly NOT proven,
 *     because provider-key provenance is pending offline (the #137 over-claim fix); and
 *   - FAILED online — the archive gate looks up gmail.com/20251104 in the public archive,
 *     finds gmail's REAL key, sees it does not match the embedded self-minted key, and
 *     rejects the verdict as a provider-key mismatch (the #136 forgery defense).
 *
 * The offline leg is hermetic; the online leg is gated behind KYSIGNED_ONLINE_E2E (it hits
 * archive.prove.email). Generated by scripts/gen-forged-key-asset.mjs.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { verifyBundleWeb } from './verifyWeb.js';
import { verifyBundle } from './verify.js';
import { runVerifyCli } from './verifyCli.js';
import { createRfc3161Provider } from '../timestamp/rfc3161/provider.js';
import { verifyWith } from '../timestamp/contract.js';
import type { TimestampProof, VerifyResult } from '../timestamp/contract.js';

const FIXTURE = fileURLToPath(new URL('../../docs/test-assets/sample-bundle-forged-key.pdf', import.meta.url));
const bundle = new Uint8Array(readFileSync(FIXTURE));
const rfc3161Only = async (proof: TimestampProof, hash: Uint8Array): Promise<VerifyResult> =>
  verifyWith([createRfc3161Provider({})], proof, hash);

describe('forged-key fixture — INTEGRITY VERIFIED offline (self-consistent, honestly NOT proven)', () => {
  it('web engine: every hard check passes, but the tier caps at INTEGRITY_VERIFIED (provenance pending)', async () => {
    const v = await verifyBundleWeb(bundle);
    assert.equal(v.signers[0].checks.dkim, true, 'DKIM verifies against the embedded self-minted key');
    assert.equal(v.signers[0].checks.attachment, true);
    assert.equal(v.signers[0].checks.intent, true);
    assert.equal(v.signers[0].checks.timestamp, true, 'the real freeTSA .tsr verifies offline');
    assert.equal(v.tier, 'INTEGRITY_VERIFIED', 'a self-consistent forgery is honestly NOT proven offline');
    assert.equal(v.signers[0].assurance.keyProvenance, 'pending');
  });

  it('node engine: identical INTEGRITY_VERIFIED verdict (web/node parity on the forgery)', async () => {
    const v = await verifyBundle(bundle, { verifyTimestamp: rfc3161Only });
    assert.equal(v.tier, 'INTEGRITY_VERIFIED', `node reasons: ${JSON.stringify(v.signers?.[0]?.reasons)}`);
    assert.equal(v.signers[0].signingDomain, 'gmail.com');
  });

  it('CLI --offline: INTEGRITY VERIFIED, exit 0 (the archive gate is online-only)', async () => {
    const { exitCode, report } = await runVerifyCli(bundle, { offline: true });
    assert.equal(exitCode, 0, report);
    assert.match(report, /OVERALL: INTEGRITY VERIFIED/);
  });
});

const ONLINE = process.env.KYSIGNED_ONLINE_E2E === '1';
describe('forged-key fixture — LIVE online: the archive gate REJECTS it (gated; real archive)', () => {
  it(
    'CLI online: FAILED with a provider-key mismatch (gmail.com/20251104 real key != the embedded key)',
    { skip: ONLINE ? false : 'set KYSIGNED_ONLINE_E2E=1 to run (hits archive.prove.email)' },
    async () => {
      const { exitCode, report, verdict } = await runVerifyCli(bundle); // online, no fakes
      assert.equal(exitCode, 1, report);
      assert.match(report, /OVERALL: FAILED/, report);
      assert.equal(verdict.signers[0].assurance.keyProvenance, 'failed');
      assert.match(JSON.stringify(verdict.signers[0].reasons), /provider key mismatch/i);
    },
  );
});
