#!/usr/bin/env node
/**
 * Regenerate the base64 font source modules (`src/pdf/fonts/dejaVuSans.ts`,
 * `dejaVuSansBold.ts`) from the vendored DejaVu Sans TTFs (#110).
 *
 * WHY base64-in-source: the run402 Cloud function is bundled by esbuild into a
 * SINGLE ESM file (scripts/run402-functions.mjs). A raw `.ttf` read via
 * `fs.readFileSync` at runtime is NOT deployed alongside that single file, so the
 * font bytes must be INLINED into the bundle. Encoding them as a string constant
 * in a `.ts` module makes esbuild embed them (the same technique as
 * src/pdf/brandLogo.ts), and keeps the module loadable under the tsx test runner
 * (which does not handle binary `.ttf` imports).
 *
 * Deterministic + reproducible: run `node scripts/embed-fonts.mjs` after replacing
 * a vendored TTF. Do NOT hand-edit the generated .ts files.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const FONT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'pdf', 'fonts');

/** @param {{ ttf: string; varName: string; out: string; label: string }} spec */
function emit(spec) {
  const bytes = readFileSync(path.join(FONT_DIR, spec.ttf));
  const b64 = bytes.toString('base64');
  const sha = createHash('sha256').update(bytes).digest('hex');
  const content =
`/**
 * ${spec.label}
 *
 * Base64-encoded ${spec.ttf} — GENERATED by scripts/embed-fonts.mjs from the
 * vendored ./${spec.ttf}. Inlined as a source module so the esbuild single-file
 * Lambda bundle carries the font bytes (see scripts/embed-fonts.mjs for why).
 * DO NOT hand-edit; regenerate with: node scripts/embed-fonts.mjs.
 *
 * License: Bitstream Vera / DejaVu (permissive) — see ./LICENSE-DejaVu.txt.
 * Source SHA-256 (${spec.ttf}): ${sha}
 */
export const ${spec.varName} =
  '${b64}';
`;
  writeFileSync(path.join(FONT_DIR, spec.out), content, 'utf8');
  console.log(`  ${spec.out} — ${bytes.length} raw bytes -> ${b64.length} base64 chars`);
}

console.log('Regenerating DejaVu Sans base64 font modules:');
emit({ ttf: 'DejaVuSans.ttf', varName: 'DEJAVU_SANS_REGULAR_BASE64', out: 'dejaVuSans.ts', label: 'DejaVu Sans (Regular) — Unicode cover/signature name font (#110).' });
emit({ ttf: 'DejaVuSans-Bold.ttf', varName: 'DEJAVU_SANS_BOLD_BASE64', out: 'dejaVuSansBold.ts', label: 'DejaVu Sans Bold — Unicode cover/signature name font (#110).' });
console.log('Done.');
