/**
 * E2E test helpers — Phase 4B (DD-13).
 *
 * Shared HTTP + fixture helpers for the kysigned e2e suite. The suite
 * exercises the full HTTP surface against a configurable BASE_URL:
 *
 *   BASE_URL=http://localhost:4022   npm run test:e2e   # local
 *   BASE_URL=https://kysigned.run402.com npm run test:e2e   # production
 *
 * The same suite is the primary DD-10 risk validation gate (first time the
 * Phase 4A CTE-based createEnvelope runs against real Postgres) AND the
 * Phase 4B ship gate (must pass against the deployed instance).
 */
import { randomBytes, randomUUID } from 'node:crypto';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PDFDocument, StandardFonts } from 'pdf-lib';

export const BASE_URL = (process.env['BASE_URL'] ?? 'http://localhost:4022').replace(/\/$/, '');

/**
 * Optional run402 anon key for the kysigned project. When set, the helpers
 * inject it as the `apikey` header on every request — required when hitting
 * the function URL directly at `https://api.run402.com/functions/v1/kysigned-api`
 * because run402's function endpoint enforces `apikeyAuth`.
 */
export const ANON_KEY = process.env['KYSIGNED_E2E_ANON_KEY'] ?? '';

/** Optional bearer token sent on every request (admin or service routes). */
export const AUTH_BEARER = process.env['KYSIGNED_E2E_AUTH'] ?? '';

/**
 * Optional e2e bypass token that tells the deployed kysigned-api Lambda to
 * swap in a no-op EmailProvider for the duration of this request. Set via
 * the project secret `KYSIGNED_E2E_BYPASS_TOKEN`.
 *
 * **Transport:** appended to the URL as `?_e2e_bypass=<token>`, NOT sent
 * as an HTTP header. The run402 function-invoke gateway only forwards three
 * headers (`authorization`, `content-type`, `apikey`) to user code and
 * strips everything else, but it forwards the full query string. Query
 * params are the only way to pass a project-scoped test flag into the
 * deployed Lambda without modifying the gateway.
 *
 * Without this, every e2e envelope creation generates real outbound email
 * → eventually flagged as spam. See [P4B.31] in kysigned-plan.md.
 */
export const E2E_BYPASS = process.env['KYSIGNED_E2E_BYPASS_TOKEN'] ?? '';

function defaultHeaders(extra?: Record<string, string>): Record<string, string> {
  const h: Record<string, string> = { 'Content-Type': 'application/json', ...(extra ?? {}) };
  if (ANON_KEY && !h['apikey']) h['apikey'] = ANON_KEY;
  if (AUTH_BEARER) h['Authorization'] = `Bearer ${AUTH_BEARER}`;
  return h;
}

/** Append the `_e2e_bypass` query param to a path when the token is set. */
function withBypass(path: string): string {
  if (!E2E_BYPASS) return path;
  const sep = path.includes('?') ? '&' : '?';
  return `${path}${sep}_e2e_bypass=${encodeURIComponent(E2E_BYPASS)}`;
}

export interface ApiResponse<T = unknown> {
  status: number;
  body: T;
  headers: Headers;
}

export async function apiPost<T = unknown>(
  path: string,
  body?: unknown,
  extraHeaders?: Record<string, string>
): Promise<ApiResponse<T>> {
  const res = await fetch(`${BASE_URL}${withBypass(path)}`, {
    method: 'POST',
    headers: defaultHeaders(extraHeaders),
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  return parseResponse<T>(res);
}

export async function apiGet<T = unknown>(
  path: string,
  extraHeaders?: Record<string, string>
): Promise<ApiResponse<T>> {
  const res = await fetch(`${BASE_URL}${withBypass(path)}`, {
    method: 'GET',
    headers: defaultHeaders(extraHeaders),
  });
  return parseResponse<T>(res);
}

async function parseResponse<T>(res: Response): Promise<ApiResponse<T>> {
  const contentType = res.headers.get('content-type') ?? '';
  let body: unknown;
  if (contentType.includes('application/json')) {
    body = await res.json().catch(() => ({}));
  } else {
    body = await res.text();
  }
  return { status: res.status, body: body as T, headers: res.headers };
}

// --- Fixture builders ---

/** Build a tiny valid PDF in-memory and return its base64 string. */
export async function makeTestPdfBase64(text = 'kysigned e2e test document'): Promise<string> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  page.drawText(text, { x: 50, y: 720, size: 14, font });
  const bytes = await doc.save();
  return Buffer.from(bytes).toString('base64');
}

/**
 * Load the canonical ACME approval form as base64. This is the fixture PDF
 * at `docs/test-assets/acme-approval.pdf` (generated by
 * `docs/test-assets/build-acme-approval.mjs`) — a deliberately-silly trial
 * document with 3 signer blocks. It is the default document used by the
 * e2e suite and is also the document recommended to forkers in the README
 * as "the kysigned trial signature document".
 *
 * Falls back to a tiny generated PDF if the fixture file is missing (e.g.
 * fresh clone without running the generator).
 */
const __helpersDir = dirname(fileURLToPath(import.meta.url));
const ACME_PDF_PATH = join(__helpersDir, '..', '..', 'docs', 'test-assets', 'acme-approval.pdf');

export async function makeAcmePdfBase64(): Promise<string> {
  if (existsSync(ACME_PDF_PATH)) {
    const bytes = readFileSync(ACME_PDF_PATH);
    return bytes.toString('base64');
  }
  // Fallback: forker hasn't generated the fixture yet. Produce a tiny
  // placeholder so the suite can still run end-to-end; real trial flows
  // should regenerate via `node docs/test-assets/build-acme-approval.mjs`.
  return makeTestPdfBase64('ACME Approval Form (placeholder — run docs/test-assets/build-acme-approval.mjs to generate the real PDF)');
}

export interface SignerSpec {
  email: string;
  name: string;
  verification_level?: 1 | 2 | 5;
}

/**
 * All e2e signers default to the `KYSIGNED_E2E_SIGNER_EMAIL` env var
 * (set it to a real inbox you control for prod e2e, so you actually receive the
 * signing-request emails during validation; unset, it falls back to a generic
 * `.test` placeholder). The `seed` becomes a Gmail plus-addressing tag so each
 * signer has a unique identity while the mail all lands in one inbox.
 */
const E2E_SIGNER_BASE = process.env['KYSIGNED_E2E_SIGNER_EMAIL'] ?? `e2e@e2e.kysigned.test`;

function taggedEmail(seed: string): string {
  const [local, domain] = E2E_SIGNER_BASE.split('@');
  if (!domain) return `${seed}+${shortId()}@e2e.kysigned.test`;
  return `${local}+${seed}-${shortId()}@${domain}`;
}

/**
 * Build a signer spec. The e2e suite defaults `verification_level: 1`
 * (click-only, no email confirmation required) to keep the create payload
 * minimal. The kysigned DB default is 2 (email confirmation required). Signing
 * itself is reply-to-sign only (the e2e suite simulates it via the
 * POST /v1/inbound/reply seam); the old Method-A `POST /v1/sign` web-signing
 * path was retired (DD-86).
 */
export function makeSigner(seed: string, opts: Partial<SignerSpec> = {}): SignerSpec {
  const signer: SignerSpec = {
    email: opts.email ?? taggedEmail(seed),
    name: opts.name ?? `${seed} ${shortId().slice(0, 4)}`,
    verification_level: opts.verification_level ?? 1,
  };
  return signer;
}

/** Short hex id used to keep fixtures unique within a test run. */
export function shortId(): string {
  return randomBytes(6).toString('hex');
}

export function newRunId(): string {
  return randomUUID().slice(0, 8);
}

/**
 * Poll a path until predicate returns true OR timeout elapses.
 * Used to wait for envelopes to reach `completed` after async bundle assembly.
 */
export async function pollUntil<T>(
  fn: () => Promise<T>,
  predicate: (val: T) => boolean,
  opts: { timeoutMs?: number; intervalMs?: number; description?: string } = {}
): Promise<T> {
  const timeoutMs = opts.timeoutMs ?? 60_000;
  const intervalMs = opts.intervalMs ?? 1_000;
  const start = Date.now();
  let last: T | undefined;
  while (Date.now() - start < timeoutMs) {
    last = await fn();
    if (predicate(last)) return last;
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  throw new Error(
    `pollUntil timed out after ${timeoutMs}ms${opts.description ? ` waiting for: ${opts.description}` : ''}`
  );
}

// --- Skip wiring ---

/**
 * Skip the calling test if the BASE_URL host is unreachable. Lets the suite
 * be authored before the local operator backend is wired up — CI runs the
 * suite against a live URL where reachability is guaranteed.
 */
export async function skipIfUnreachable(t: { skip: (msg?: string) => void }): Promise<void> {
  try {
    const res = await fetch(`${BASE_URL}/v1/health`, {
      headers: ANON_KEY ? { apikey: ANON_KEY } : undefined,
    }).catch(() => null);
    // 404 is fine — server is reachable, just doesn't have /v1/health yet.
    // ECONNREFUSED returns null from .catch(() => null).
    if (!res) {
      t.skip(`BASE_URL ${BASE_URL} unreachable — skipping e2e (set BASE_URL to a live deployment to enable)`);
    }
  } catch {
    t.skip(`BASE_URL ${BASE_URL} unreachable`);
  }
}
